### ISSUE TITLE
Question for the maintainers

### ISSUE THREAD

**Issue by Houlistonm** [tomtom-international/alertmanager-webhook-logger#8]
I have forked the repo, updated to go 1.21, converted from kit/log to log/slog, and reduced the imports to prometheus/alertmanager/template.  
All tests are passing.
Any interest in a PR?

**Comment by jackhammer2k** [comment]
Hi! On principle we are always interested in PRs, but can you please elaborate why you did these changes (apart from the update)? What are the advantages?

**Comment by YvesMueller-TomTom** [comment]
FIY, updated to 1.21 in  #12

**Comment by YvesMueller-TomTom** [comment]
Thanks for the suggested changes

- [x] updated to go 1.23
- [x] reduced imports for Prometheus

Since we don't have any arguments to replace kit/log with log/slog, we will keep it as is. As a result I would like to close the issue.
